language: rust

env:
  global:
    - secure: cpmR5hxPE81S6x/AEKagQfs6Rlr+632kxcYb59Et4aFjmC+LxXjTuAUtOVeBptIXE6y5fB/3fVV4y4hgPUucwSBWM14JqHUlB/mMjEstMnf+cVaRpn4S6zjXWZ7+4SZHuLyCJUInWM7EShSH82cANbI3IZhzINVzfRVRVwAYF8s=

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq valgrind

script:
  - cargo build --verbose
  - wget 'http://en.wikipedia.org'
  - cargo test --verbose
  - cargo doc --verbose
  - cargo build --release
  - cat index.html | wc
  - valgrind target/release/test_std
  - valgrind target/release/test_lines
  - ./check-line-length.sh

after_success:
  - '[ "${TRAVIS_PULL_REQUEST}" = "false" ] && bash upload-docs.sh'

branches:
  only: master

notifications:
  email:
    on_success: never
